# Generated by Django 4.2.11 on 2024-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "company_id_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_nationality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_sector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_contact",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                ("representatives", models.IntegerField(blank=True, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "relationship_status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=8,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
