# Generated by Django 4.2.11 on 2024-03-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CotizacionRealizada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_Id", models.IntegerField()),
                ("User_Name", models.CharField(max_length=200)),
                ("Formulario", models.CharField(max_length=200)),
                ("Nombre_Proveedor", models.CharField(max_length=200)),
                ("Rut_Proveedor", models.CharField(max_length=200)),
                ("Empresa", models.CharField(max_length=200)),
                ("Area", models.CharField(max_length=200)),
                ("Centro_Costo", models.CharField(max_length=200)),
                ("Nombre_Solicitante", models.CharField(max_length=200)),
                ("Nombre_Autoriza", models.CharField(max_length=200)),
                ("hora_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Estado_Solicitudes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Request_Status",
                    models.CharField(default="Solicitud Creada", max_length=200),
                ),
                ("Solicitud_Creada", models.BooleanField(default=True)),
                ("Solicitud_Revision", models.BooleanField(default=False)),
                ("Solicitud_Aprobada", models.BooleanField(default=False)),
                ("Solicitud_Finalizada", models.BooleanField(default=False)),
                (
                    "Hora_Inicio_Solicitud_Creada",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "Hora_Inicio_Solicitud_Revision",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "Hora_Inicio_Solicitud_Aprobada",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "Hora_Inicio_Solicitud_Finalizada",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "ID_OC",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="request.cotizacionrealizada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CotizacionRealizada_Productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre_Producto", models.CharField(max_length=200)),
                ("Cantidad", models.IntegerField()),
                ("Descripcion_Producto", models.CharField(max_length=200)),
                (
                    "ID_OC",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="request.cotizacionrealizada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CotizacionRealizada_Archivos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File_Number", models.IntegerField()),
                ("File_Name", models.CharField(max_length=200)),
                ("File_Type", models.CharField(max_length=200)),
                (
                    "ID_OC",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="request.cotizacionrealizada",
                    ),
                ),
            ],
        ),
    ]
