# Generated by Django 4.2.11 on 2024-03-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("number", models.IntegerField()),
                ("date", models.DateField()),
                ("dropdown", models.CharField(max_length=200)),
                ("checkbox", models.BooleanField()),
                ("radios", models.CharField(max_length=200)),
                ("range", models.IntegerField()),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
