# Generated by Django 4.2.11 on 2024-03-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacionrealizada_productos",
            name="Descripcion_Producto",
            field=models.TextField(),
        ),
    ]
