# Generated by Django 4.2.11 on 2024-03-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0002_alter_cotizacionrealizada_productos_descripcion_producto"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacionrealizada",
            name="Numero_Factura",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="cotizacionrealizada",
            name="Numero_Orden_compra",
            field=models.CharField(default="", max_length=200),
        ),
    ]
