# Generated by Django 4.2.11 on 2024-03-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0003_cotizacionrealizada_numero_factura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estado_solicitudes",
            name="Hora_Inicio_Solicitud_Ajuste_Informacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estado_solicitudes",
            name="Solicitud_Ajuste_Informacion",
            field=models.BooleanField(default=False),
        ),
    ]
