# Generated by Django 4.2.11 on 2024-03-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "request",
            "0004_estado_solicitudes_hora_inicio_solicitud_ajuste_informacion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacionrealizada",
            name="texto_ajuste_informacion_solicitud",
            field=models.TextField(default=""),
        ),
    ]
